services:
  openssh-server:
    build: ./openssh
    environment:
      - PUID=1000
      - PGID=1000
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=test
      - USER_NAME=test
    ports:
      - "${SSH_PORT}:2222"
    volumes:
      - ./openssh/config:/custom-cont-init.d:ro
    restart: unless-stopped

  web1.ctf:
    image: php:8.2-apache-bookworm
    volumes:
      - ./web1/index.php:/var/www/html/index.php
    restart: unless-stopped

  web2.ctf:
    image: php:8.2-apache-bookworm
    volumes:
      - ./web2/index.php:/var/www/html/index.php
    restart: unless-stopped

  healtcheck:
    build: ./healthcheck
    ports:
      - "${HTTP_PORT}:8080"
    restart: unless-stopped
