name: SonarCloud analysis

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=KianBankeLarsen_CTF-Platform
            -Dsonar.organization=kianbankelarsen
            -Dsonar.scm.exclusions.disabled=true
            -Dsonar.c.file.suffixes=- 
            -Dsonar.cpp.file.suffixes=- 
            -Dsonar.objc.file.suffixes=-
            -Dsonar.exclusions=/src/application/welcome/neumorphism/_js/vendors/**,/src/application/welcome/neumorphism/_sass/vendors/**